Acceptance Testing (#10)
* Set docker support for identity server.

	token is not issuing due to following error

	System.UnauthorizedAccessException: Access to the path '/app/keys/is-signing-key-0220A831E6397573DE6552C3B67CC06C.json' is denied.
 ---> System.IO.IOException: Permission denied

* Test running? hacky way!

* Reset github worklow to old version

* Add Ui.AcceptanceTesting project.

    - completed Login senario

* Add log out senario

* Add docker support for unified project

* Completed AcceptanceTesting to match with new unified project

* Add AcceptanceTesting project to CPM

* Add WebApplicationFactory to automate the tests in CI

* Update github workflows

* Collect test coverage

* Install playwright browsers

* Change shell to pwsh in playwright installation

* Setup code Coverage