Set docker support for identity server.
	token is not issuing due to following error

	System.UnauthorizedAccessException: Access to the path '/app/keys/is-signing-key-0220A831E6397573DE6552C3B67CC06C.json' is denied.
 ---> System.IO.IOException: Permission denied